def causeError():
    return 1/0

print(causeError())